# Generated by Django 3.0.2 on 2020-01-16 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avr_rigney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightmodule',
            name='number_of_relays_used',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
